// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnbbktabxgpycvarorxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuYmJrdGFieGdweWN2YXJvcnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTg4NzksImV4cCI6MjA2MzQzNDg3OX0.eeY3tYE_PGZfzmQeuzwDmAxUCcv-gYz5mYUhi1v3OSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);